=== msieker/resume/resumeschema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string"
        },
        "personalInfo": {
            "$ref": "#/definitions/personalInfo"
        },
        "highlights": {
            "type": "array",
            "items": {
                "type":"string"
            },
            "default": []
        },
        "skills": {
            "type":"array",
            "items":{"$ref": "#/definitions/skillItem"},
            "default": []
        },
        "work": {
            "type":"array",
            "items":{"$ref": "#/definitions/workItem"},
            "default": []
        },
        "projects": {
            "type":"array",
            "items":{"$ref": "#/definitions/projectItem"},
            "default": []
        }
    },
    "additionalProperties": false,
    "definitions": {
        "personalInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                }
            }
        },
        "skillItem": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "workItem": {
            "type": "object",
            "properties": {
                "employer": {
                    "type": "string"
                },
                "position":{
                    "type": "string"
                },
                "location":{
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "highlights":{
                    "type":"array",
                    "items": {"type":"string"}
                }
            }   
        },
        "projectItem":{
            "type": "object",
            "properties": {
                "name":{"type":"string"},
                "employer":{"type":"string"},
                "dateRange":{"type":"string"},
                "technologies":{
                    "type": "array",
                    "items": {"type":"string"}
                },
                "role":{"type":"string"},
                "teamSize":{"type":"number"},
                "responsibilities":{"type":"string"},
                "description":{"type":"string"}
            }
        }
    }
}

=== msieker/resume/resume.json
{
    "personalInfo": {
        "name": "Matt Sieker",
        "email": "matt@siekernet.com",
        "location": "Kansas City, MO"
    },
    "highlights": [
        "15+ Years of .NET Development experience, from early betas of .NET 1 through .NET Core 3",
        "Experience developing for web, desktop, backend, and cloud",
        "Strong drive for self-education and personal growth",
        "Works well as both a lone programmer and a member of a team",
        "Can manage a project from initial requirements gathering through production deployment"
    ],
    "skills": [
        {
            "category": "Web Technologies",
            "skills": [
                "ASP.NET",
                "ASP.NET MVC",
                "Razor",
                "CSS",
                "HTML",
                "React",
                "Redux"
            ]
        },
        {
            "category": "Languages",
            "skills": [
                "C#",
                "Python (2/3)",
                "Javascript",
                "Typescript",
                "Perl",
                "Powershell",
                "BASH scripting",
                "T-SQL"
            ]
        },
        {
            "category": "Databases",
            "skills": [
                "Sql Server 2000-2017 & Azure",
                "Sqlite",
                "PostgreSQL"
            ]
        },
        {
            "category": "Tooling",
            "skills": [
                "Git",
                "Docker",
                "RabbitMQ",
                "Redis",
                "Azure Devops CI",
                "Windows Azure (Virtual Machines, Container Deployment, Batch, Logic Apps, Function Apps)"
            ]
        },
        {
            "category": "Operating Systems",
            "skills": [
                "Windows",
                "Windows Server 2003-2012",
                "Ubuntu/Debian",
                "Gentoo"
            ]
        },
        {
            "category": "Other",
            "skills": [
                "Active Directory Administration & Setup",
                "Exchange Administration & Setup",
                "Network Management",
                "Hardware Troubleshooting",
                "SQL Server Installation and Maintenance"
            ]
        }
    ],
    "work": [
        {
            "employer": "Independent Consultant",
            "location": "Kansas City, MO",
            "position": "Developer/Architect/Infrastructure Management",
            "startDate": "September 2017",
            "endDate": "Current",
            "highlights": [
                "Implemented probabilistic genotyping system that wraps around a well-validated R library with Python, and using Docker containers on Azure Batch, allowed massively parallel processing of cases."
            ]
        },
        {
            "employer": "The Nerdery",
            "location": "Kansas City, MO",
            "position": "Developer",
            "startDate": "April 2016",
            "endDate": "September 2017",
            "highlights": [
                "Created lead collection sites for a major local insurance company that integrated with Docusign",
                "Found, documented, and reported several security flaws in various clientâ€™s existing systems."
            ]
        },
        {
            "employer": "Biomedical Systems",
            "location": "St. Louis, MO",
            "position": "Developer",
            "startDate": "September 2013",
            "endDate": "March 2016",
            "highlights": [
                "Maintained and enhanced legacy systems.",
                "Architected system to communicate clinical data with large pharmaceutical company",
                "Implemented Domain Specific Language and supporting tools to allow non-technical users to create rules to verify data integrity"
            ]
        },
        {
            "employer": "MDI Achieve",
            "location": "St. Louis, MO",
            "position": "Developer/Architect/Infrastructure Management",
            "startDate": "March 2013",
            "endDate": "September 2013"
        },
        {
            "employer": "Gravit8",
            "location": "St. Louis, MO",
            "position": "Developer/Architect/Infrastructure Management",
            "startDate": "April 2012",
            "endDate": "February 2013"
        },
        {
            "employer": "Unidev",
            "location": "St. Louis, MO",
            "position": "Developer/Architect",
            "startDate": "April 2011",
            "endDate": "April 2012"
        },
        {
            "employer": "Haas Group International (Formally Avchem, Inc.)",
            "location": "St. Louis, MO",
            "position": "Developer/Architect",
            "startDate": "April 2006",
            "endDate": "April 2011"
        }
    ],
    "projects": [
        {
            "name": "Request Module Update",
            "employer": "Avchem",
            "dateRange": "2006",
            "teamSize": 2,
            "role": "Developer",
            "responsibilities": "Design and Implementation",
            "technologies": ["VB.Net", "ASP.Net", "SQL Server", "Javascript"],
            "description": "The request module allows customers to define a form and workflow for a process. This was then added to the system where end-users could submit requests for a process. The update added several features: graphical designers for both the form and workflow, with the workflow editor displaying a dynamically generated flowchart for the current workflow; the ability to have a step on the workflow be subdivided into several approvals that can be done in parallel; redirecting the workflow based on fields on the form; and the ability to create groups of users to be included on a workflow step, that can inherit users from sites above, and allows for easier maintenance; and the ability to import and export definitions of requests between instances (training, production, etc). Existing data was transformed and adapted to newer standards either on the fly, for simple changes, or with a Python script that was run during deployment."
        }
    ],
    "$schema": "./resumeschema.json"
}

=== msieker/resume/data.json
{
    "personalInfo": {
        "name": "Matt Sieker",
        "email": "matt@siekernet.com",
        "location": "Kansas City, MO"
    },
    "highlights": [
        "15+ Years of .NET Development experience, from early betas of .NET 1 through .NET Core 3",
        "Experience developing for web, desktop, backend, and cloud",
        "Strong drive for self-education and personal growth",
        "Works well as both a lone programmer and a member of a team",
        "Can manage a project from initial requirements gathering through production deployment"
    ],
    "skills": [
        {
            "category": "Web Technologies",
            "items": [
                "ASP.NET",
                "ASP.NET MVC",
                "Razor",
                "CSS",
                "HTML",
                "React",
                "Redux"
            ]
        },
        {
            "category": "Languages",
            "items": [
                "C#",
                "Python (2/3)",
                "Javascript",
                "Typescript",
                "Perl",
                "Powershell",
                "BASH scripting",
                "T-SQL"
            ]
        },
        {
            "category": "Databases",
            "items": [
                "Sql Server 2000-2017 & Azure",
                "Sqlite",
                "PostgreSQL"
            ]
        },
        {
            "category": "Tooling",
            "items": [
                "Git",
                "Docker",
                "RabbitMQ",
                "Redis",
                "Azure Devops CI",
                "Windows Azure (Virtual Machines, Container Deployment, Batch, Logic Apps, Function Apps)"
            ]
        },
        {
            "category": "Operating Systems",
            "items": [
                "Windows",
                "Windows Server 2003-2012",
                "Ubuntu/Debian",
                "Gentoo"
            ]
        },
        {
            "category": "Other",
            "items": [
                "Active Directory Administration & Setup",
                "Exchange Administration & Setup",
                "Network Management",
                "Hardware Troubleshooting",
                "SQL Server Installation and Maintenance"
            ]
        }
    ],
    "work": [
        {
            "employer": "Independent Consultant",
            "location": "Kansas City, MO",
            "position": "Developer/Architect/Infrastructure Management",
            "startDate": "September 2017",
            "endDate": "Current",
            "highlights": [
                "Implemented probabilistic genotyping system that wraps around a well-validated R library with Python, and using Docker containers on Azure Batch, allowed massively parallel processing of cases."
            ]
        },
        {
            "employer": "The Nerdery",
            "location": "Kansas City, MO",
            "position": "Developer",
            "startDate": "April 2016",
            "endDate": "September 2017",
            "highlights": [
                "Created lead collection sites for a major local insurance company that integrated with Docusign",
                "Found, documented, and reported several security flaws in various clientâ€™s existing systems."
            ]
        },
        {
            "employer": "Biomedical Systems",
            "location": "St. Louis, MO",
            "position": "Developer",
            "startDate": "September 2013",
            "endDate": "March 2016",
            "highlights": [
                "Maintained and enhanced legacy systems.",
                "Architected system to communicate clinical data with large pharmaceutical company",
                "Implemented Domain Specific Language and supporting tools to allow non-technical users to create rules to verify data integrity"
            ]
        },
        {
            "employer": "MDI Achieve",
            "location": "St. Louis, MO",
            "position": "Developer/Architect/Infrastructure Management",
            "startDate": "March 2013",
            "endDate": "September 2013"
        },
        {
            "employer": "Gravit8",
            "location": "St. Louis, MO",
            "position": "Developer/Architect/Infrastructure Management",
            "startDate": "April 2012",
            "endDate": "February 2013"
        },
        {
            "employer": "Unidev",
            "location": "St. Louis, MO",
            "position": "Developer/Architect",
            "startDate": "April 2011",
            "endDate": "April 2012"
        },
        {
            "employer": "Haas Group International (Formally Avchem, Inc.)",
            "location": "St. Louis, MO",
            "position": "Developer/Architect",
            "startDate": "April 2006",
            "endDate": "April 2011"
        }
    ],
    "projects": [],
    "$schema": "./data.schema.json"
}
